application: papertlogo
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /error
  static_files: static/error.txt
  upload: static/error.txt

- url: /moderate
  script: moderate.py

- url: /.*
  script: index.py
